name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "iniciando login to docker hub"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build docker image
      run: | 
        echo "building the image"
        docker build -t williansrb81/graphql:0.0.2 .
    - name: push image to docker
      run: |
        echo "pushing the image to docker hub"
        docker push williansrb81/graphql:0.0.2
      
        
#   - name: Build the Docker image
#     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
