name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
          
    - name: docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        echo "iniciando login to docker hub"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: | 
        echo "building the images"
        docker build -t williansrb81/graphql:$NEW_VERSION .
        docker build -t williansrb81/graphql:latest .
    - name: push image to docker
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        echo "pushing the image to docker hub"
        docker push williansrb81/graphql:$NEW_VERSION
        docker push williansrb81/graphql:latest
      
        
#   - name: Build the Docker image
#     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
